### ISSUE TITLE
Requirements are incorrect: "make[1]: rice: Command not found"

### ISSUE THREAD

**Issue by 0xSheepdog** [ninech/reception#5]
platform:
centos7 & rhel7 minimal build and web-server build with working docker/docker-compose

```
[user@docker opt]$ sudo git clone https://github.com/ninech/reception.git
Cloning into 'reception'...
remote: Enumerating objects: 163, done.
remote: Total 163 (delta 0), reused 0 (delta 0), pack-reused 163
Receiving objects: 100% (163/163), 91.88 KiB | 0 bytes/s, done.
Resolving deltas: 100% (71/71), done.
[user@docker opt]$ cd reception/
[user@docker reception]$ ls
common  contrib  dns  docker  go.mod  go.sum  http  LICENSE  Makefile  README.md  reception.go  resources  VERSION
[user@docker reception]$ sudo make
make[1]: rice: Command not found
make[1]: *** [clean] Error 127
make: *** [http] Error 2
```

**Comment by cimnine** [comment]
Thank you for reporting this. I recognize that there were some problems with the dependencies, i.e. they were very outdated.

But I believe the problem here is that `$GOPATH/bin` is not part of your `$PATH`. See https://github.com/golang/go/wiki/GOPATH#integrating-gopath. Am I right with this conclusion or is the problem something else?

**Comment by 0xSheepdog** [comment]
> But I believe the problem here is that `$GOPATH/bin` is not part of your `$PATH`.

This is indeed the problem...but for a different reason. I don't have GO installed on the server I run the containers on... Thank you for your response.
